### ISSUE TITLE
Object Reference Exception on the simplest of Setups or Verifys

### ISSUE THREAD

**Issue by StuartHemming** [rgvlee/Moq.Contrib.ExpressionBuilders.Logging#8]
Running a .Net Core 3.1 app with Moq 4.14.5, Microsoft.Extensions.Logging 3.1.7

Test contains this ...

```
    Mock<ILogger<IndexModel>> _logger;
    _logger = new Mock<ILogger<IndexModel>>();
    _logger.Setup(_ => Log.With.LogLevel(LogLevel.Error)).Verifiable();
    Mock.Verify(_logger);
```

When run it returns
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Moq.ExpressionExtensions.<Split>g__Split|5_0(Expression e, Expression& r, InvocationShape& p, Boolean assignment)
   at Moq.ExpressionExtensions.Split(LambdaExpression expression)
   at Moq.Mock.SetupRecursive[TSetup](Mock mock, LambdaExpression expression, Func`4 setupLast)
   at Moq.Mock.Setup(Mock mock, LambdaExpression expression, Condition condition)
   at Moq.Mock`1.Setup[TResult](Expression`1 expression)
   at -- Location of the call to _logger.Setup()
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by rgvlee** [comment]
Change

```
  _logger.Setup(_ => Log.With.LogLevel(LogLevel.Error)).Verifiable();
```

to 

```
  _logger.Setup(Log.With.LogLevel(LogLevel.Error)).Verifiable();
```

**Comment by rgvlee** [comment]
As the above should resolve your issue, I'm closing this issue for now. If you are still having issues please let me know.
